### ISSUE TITLE
some questions about background of images

### ISSUE THREAD

**Issue by SugarMasuo** [cvlab-stonybrook/doc3D-dataset#1]
Thank you so much for your sharing. I have some misunderstanding of the data.

- As following picture, there is a black block in the background around document of some input images. It's for improving the training result or other special reason? And the pixel value is set (6,6,6) get confused on this too.
![image](https://user-images.githubusercontent.com/15923907/65224170-3acf0800-daf5-11e9-9070-da49954bdb47.png)

- The value of background pixel in depth map is zero, but it's diffderent in 3D coordinate map, how to calcuate its X^(3D) = K^(-1) [i,j,d_ij]^T to get [0.512,0.498,0.498] ？ 
![image](https://user-images.githubusercontent.com/15923907/65224276-7073f100-daf5-11e9-8c4c-8ef2a6222531.png)

Looking forward your reply. Thank you !

**Comment by sagniklp** [comment]
- It's because of the rendering procedure. The weird thing comes from the environment map. We augment the background at training time. You can use the uv, or wc to obtain a mask and replace the background.
- We regress 3D in image space, no need to do the projection. The background should be zero. In this case when the 3D coords. map is normalized (line 46-49) the background becomes non-zero. Just use the previously mask to make it zero.

**Comment by SugarMasuo** [comment]
- The first question is in abeyance until I know more about it. Thank you~

- First of all, what we said 3D coordinate，3D coordinate map, coordinates of point cloud, are the same thing?  
In training period,  regress 3D coordinate in image space, no need to do the projection. 
What is different in calculating groundtruth of  3D coords ( C ),  which should be obtained by coordinate transformation with intrinsic matrix X.  Am I right?

When observing the downloaded data, I know the value of background pixel in depth map is normalized to zero, I can understand that. However, the value of background pixel in 3D coordinate images is all same, which is [0.512,0.498,0.498]. This is the most confusing thing for me. 
The value of X and Y shouldn't be different for each pixel?
These value of background pixel in 3D coordinate should be set to zero using mask in training process? 

Look forward to your reply~

**Comment by sagniklp** [comment]
- When we refer to 3D coordinates it means the 3D coordinate maps, i.e. physical mesh coordinates rendered using a camera. This is a dense representation. (R,G,B) Value in each pixel correspond to a 3D coordinate (X,Y,Z). On the other hand, coordinates of a pointcloud is sparse which is harder to train with. At rendering time the dense image space RGBs are interpolated from sparse points (XYZ), thus can be considered as the groundtruth 3d coords. No need to obtain apply the intrinsic matrix in this case. I think that answers your question.
- If you inspect the unnormalized 3D coordinates you'll see the background is (0,0,0). Now the raw coords. are in [-a,b] when we normalize it in [0,1] the background becomes (0.512,0.498,0.498).

**Comment by SugarMasuo** [comment]
Got it! Thank you so much~
