### ISSUE TITLE
about resolution

### ISSUE THREAD

**Issue by fh2019ustc** [cvlab-stonybrook/doc3D-dataset#12]
Hi, 
Now I can't download the dataset, so I want to know the resolution of distorted image size in the dataset.
Besides, in your paper you resize the training image to 256 ×256 and resize the output to original size fanaly，does this operation affect the performance. Have  you try croping the image and then put the crops into the network, and stitch the output finaly.

**Comment by sagniklp** [comment]
No, we haven't tried cropping and stitching in this network
