### ISSUE TITLE
about meshes (.obj files) 

### ISSUE THREAD

**Issue by fh2019ustc** [cvlab-stonybrook/doc3D-dataset#13]
Hi~,
I am very interested in your work!
Very thanks for your public of the dataset!
And I want to know , when you will release the meshes (.obj files).
Thank you~!

**Comment by JasonBoy1** [comment]
I cannot unzip the mesh files.

**Comment by zjupx** [comment]
Need mesh files(.obj files) too!  Will you release the raw files?

**Comment by sagniklp** [comment]
Please send me an email at sadas@cs.stonybrook.edu
