### ISSUE TITLE
Download Doc3d Dataset

### ISSUE THREAD

**Issue by Antollo** [cvlab-stonybrook/doc3D-dataset#19]
Hello, I filled out the form a few days ago. Could you please send me the username and password (my email address is antoninowinowski@gmail.com)?

**Comment by Aiden0609** [comment]
Hi, did you receive the username in the end? I filled out the form but haven't received anything either.

**Comment by Antollo** [comment]
Yes, I received it. I am sorry, but I didn't notice and ended up not using it. Thanks anyway.
