### ISSUE TITLE
UV MAP

### ISSUE THREAD

**Issue by lsabrinax** [cvlab-stonybrook/doc3D-dataset#20]
Thank you for your sharing! I have a question about the UV MAP, I know uv[:,:,0] defines foreground or background, but I want to know whether the uv[:,:,1] defines the x  coordinate and the uv[:,:,2] defines the y coordinate.

**Comment by KingRicardo** [comment]
Hi bro, I missed the uv_9.zip in doc3d dataset. But the data server is unfortunately down. Could you send me a copy of uv_9.zip in email(a1446534711@163.com) or google disk?

**Comment by sagniklp** [comment]
The data server is back online. I appreciate your patience and apologies for the inconvenience.
