### ISSUE TITLE
doc3d dataset 403 forbidden 

### ISSUE THREAD

**Issue by cjt222** [cvlab-stonybrook/doc3D-dataset#22]
Hello, thank you for contributing such an excellent work. Excuse me, I tried to download the doc3d dataset, but it kept reporting 403 forbidden when downloading it. Is there a problem with the server? When will the server be repaired? thanks

**Comment by KingRicardo** [comment]
Same problem

**Comment by sagniklp** [comment]
We were having data storage issues. It is solved now. Please retry downloading. Apologies for the inconvenience!
