### ISSUE TITLE
Questions about wc datasets

### ISSUE THREAD

**Issue by jyh2378** [cvlab-stonybrook/doc3D-dataset#23]
Many thanks for your sharing.
I have some difficult for understanding of the 3d coordinate(wc) datasets.
In your data, 3d coordinate value has small range.
```
xmx, xmn, ymx, ymn,zmx, zmn= 1.2539363, -1.2442188, 1.2396319, -1.2289206, 0.6436657, -0.67492497     ## value obtained from the entire dataset
```
Could you let me know what value in wc dataset means?
I want to know what value of "one" means in your wc dataset.
Also, can this 3d coordinate value have [-inf, inf] range in theory?

**Comment by sagniklp** [comment]
All the meshes are aligned (rigid transformation) with a planar mesh defined in [-1.5, 1.5]. Learning unbounded real values for a regression task is challenging therefore we do this alignment step.
