### ISSUE TITLE
About dataset license

### ISSUE THREAD

**Issue by Soongja** [cvlab-stonybrook/doc3D-dataset#24]
Hi,
I saw that this code repo is under MIT license, but I'm not sure if the dataset is as well.
Can I use the doc3D dataset to train a model for commercial purposes?

**Comment by sagniklp** [comment]
Yes, you can, but remember that all the textures (the content of the documents) may not be copyright-free. We tried to use open-source images but can't guarantee the fact.

**Comment by Soongja** [comment]
I understand. Thank you for the reply.
