### ISSUE TITLE
Has doc3D dataset beed updated recently？

### ISSUE THREAD

**Issue by renmada** [cvlab-stonybrook/doc3D-dataset#25]
I’m reproducing https://github.com/cvlab-stonybrook/PaperEdge. It's weird that most of file in [list](https://github.com/cvlab-stonybrook/PaperEdge/blob/main/data/doc3d_trn.txt) given by repo can not be found in doc3d dataset I downloaded 2 weeks ago.

**Comment by sagniklp** [comment]
That's weird. I can investigate this. We had a server issue last year, so we had to move and rezip the files. Could you check if the folders are wrong or if the files are missing?

**Comment by sagniklp** [comment]
I hope you were able to figure out that folder names are jumbled.
