### ISSUE TITLE
Username and Password not Recieved

### ISSUE THREAD

**Issue by Aiden0609** [cvlab-stonybrook/doc3D-dataset#26]
Many thanks for your work, and it's a splendid dataset you've made. I wish to use Doc3D as the training set for my document image rectify network, but I have not received any password or username after I filled out the Google Form to request one. This dataset is ideal for my project, and it is important to me, so could you please check if my Google Form submission is properly done and send me the username and password for download? Thank you, I really need this dataset.

**Comment by sagniklp** [comment]
I have sent out username passwords to people who submitted the form in the last 24 hrs. If you did not get it then please resubmit the form.
