### ISSUE TITLE
Google Form is Closed

### ISSUE THREAD

**Issue by Dawars** [cvlab-stonybrook/doc3D-dataset#28]
Hi, 
I'd like to get access to the dataset but the linked google form (https://forms.gle/RTfi7LUSrt891VuN8) doesn't work any more:

```
The form Doc3D dataset request form is no longer accepting responses.
Try contacting the owner of the form if you think that this is a mistake.
```

Could you re-enable it, please?

**Comment by sagniklp** [comment]
It is a storage issue of Google Drive. Could you send me an email at sadas@cs.stonybrook.edu?
