### ISSUE TITLE
Document creation from mesh

### ISSUE THREAD

**Issue by Enuvesta** [cvlab-stonybrook/doc3D-dataset#3]
Hi!
I was wondering, how exactly do you get your final documents from meshes?  Is there some kind of mapping procedure?

Thanks!

**Comment by sagniklp** [comment]
It's done using [Blender](https://www.blender.org/), a 3D modeling software. We will make the rendering code available soon!

**Comment by sagniklp** [comment]
Rendering code is now available here: https://github.com/sagniklp/doc3D-renderer

**Comment by Enuvesta** [comment]
Thank you so much!
