### ISSUE TITLE
Credentials for download of dataset

### ISSUE THREAD

**Issue by pretto0** [cvlab-stonybrook/doc3D-dataset#35]
Hi there!
Thanks for your contribute with this dataset. I filled out the form, but I haven't received the dataset credentials yet.
Kindly share the same or let me know if there are any issues.
Email: qw153752117@gmail.com

**Comment by xddzb** [comment]
ccbxqc@163.com i need the download link too. thank you very much

**Comment by fh2019ustc** [comment]
@pretto0 请你不要把我上传的百度网盘数据集到处发

**Comment by pretto0** [comment]
> @pretto0 请你不要把我上传的百度网盘数据集到处发

好的，是上面这位同学邮件发我寻求了，我不会再外传给任何人了。
