### ISSUE TITLE
Can not download img_8 and uv_6

### ISSUE THREAD

**Issue by SugarMasuo** [cvlab-stonybrook/doc3D-dataset#5]
Tip is no privileges, thanks!

**Comment by SugarMasuo** [comment]
Tip is no privileges, thanks!

**Comment by sagniklp** [comment]
Looking into it, thanks for letting me know!

**Comment by SugarMasuo** [comment]
I try it again, but the same problem.
![image](https://user-images.githubusercontent.com/15923907/65563790-52871000-df7d-11e9-8305-ba0432947e85.png)

**Comment by sagniklp** [comment]
The link is up now! Sorry for the late response.
