### ISSUE TITLE
the type of L_D ( reconstruction loss)

### ISSUE THREAD

**Issue by SugarMasuo** [cvlab-stonybrook/doc3D-dataset#9]
Hello~ the L_2 loss of reconstruction for the unwarped image is F norm of a matrix？

**Comment by sagniklp** [comment]
Yes. Just use pytorch MSE.

**Comment by SugarMasuo** [comment]
Do you still take the square root of MSE loss? Or it dosen't matter ?

**Comment by sagniklp** [comment]
Doesn't matter!
